### ISSUE TITLE
Создать генератор событий

### ISSUE THREAD

**Issue by VisualVortex** [ya-shred/frontend#4]
## Создать генератор событий.

Если правильно понял: Генератор событий, который генерирует и отправляет события в Window.
- [ ] 1. Создать функцию - генератор событий.
- [ ] 2. Создать следующие события: 
  - [ ] a. Новое сообщение.
  - [ ] b. Добавлен пользователь.
  - [ ] c. Пользователь ушел.
- [ ] 3. События должны отправляться в Window

**! ! ! Поправьте меня если кто в курсе данной темы.**

**Comment by EAndreyF** [comment]
Думаю скорее тут нужно написать некую надстройку над клиентской библиотекой сокетного сервера. Которая будет мокать подключения к сокетному серверу и вместо него отправлять необходимые сообщения.
